[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[scheduled-functions]]
  name = "cron"
  schedule = "*/5 * * * *"
  path = "/api/cron"
