[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/history"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=300, stale-while-revalidate=60"
